### ISSUE TITLE
Organization folders

### ISSUE THREAD

**Issue by JLefortBesnard** [marctoutain/ED_prediction#3]
**Hi there,**

**In order for you to get your hand dirty with Github, I suggest you start with an easy mission : reorganization of your code in that way (which will ensure reproducible results):**

_clustering.py_ (clustering analysis + saving as df)
_visualization_clustering.py_ (opening of previous results df + visualization)
_benchmarking.py_ (nested CV benchmark analysis + saving results as df)
_prediction.py_ (5 fold analysis with winning model loaded from previous results df+ saving as dataframe)
_significance.py_ (load previous results df + check significant weights)
_visualisation_predicition.py_ (load 2 previous results df + visualization)

**I wrote .py but .ipynb files are fine**
**Sounds good to you? If so, you can assign yourself and run your first PR !**

**Comment by marctoutain** [comment]
Hi,

Alright I'm on it.
